# Generated by Django 3.1.7 on 2021-05-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmessege',
            name='msg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='msgs.message', unique=True, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
