# Generated by Django 3.1.7 on 2021-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_classmessege_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmessege',
            name='recipient',
        ),
    ]
