# Generated by Django 3.1.7 on 2021-05-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210514_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0003_remove_classmessege_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Class', to='classes.classes', verbose_name='Class')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.DeleteModel(
            name='ClassMessege',
        ),
        migrations.AddField(
            model_name='classmessage',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='msg', to='msgs.message', unique=True, verbose_name='Message'),
        ),
    ]
