# Generated by Django 3.1.7 on 2021-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_auto_20210516_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='sent at'),
        ),
    ]
