# Generated by Django 3.1.7 on 2021-03-27 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheduletime',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
            preserve_default=False,
        ),
    ]
