# Generated by Django 3.1.7 on 2021-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
