# Generated by Django 3.1.7 on 2021-05-05 17:42

import backend.classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210505_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.CharField(default=backend.classes.models.uuid64bit, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
