# Generated by Django 3.1.7 on 2021-04-01 14:10

import backend.classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classes_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='uuid',
            field=models.CharField(default=backend.classes.models.uuid64bit, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
