# Generated by Django 3.1.7 on 2021-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210401_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='uuid',
            new_name='id',
        ),
    ]
