# Generated by Django 3.1.7 on 2021-05-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.classes', unique=True),
        ),
    ]
