# Generated by Django 3.1.7 on 2021-05-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210507_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='classes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
    ]
