# Generated by Django 3.1.7 on 2021-04-01 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_auto_20210401_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='class_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
